name: opfiles Bot

on:
  push:
    paths:
      - 'Records/opfiles.txt'
      - '.github/workflows/opfiles.yml'
  workflow_dispatch:

env:
  GitHubMail: "95846079+inferious-king@users.noreply.github.com"
  GitHubName: "inferious-king"

jobs:
  op_bot:
    runs-on: ubuntu-20.04
    steps:
      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
      - uses: styfle/cancel-workflow-action@0.9.0
        name: "Cancel duplicate runs"
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - name: Setup Py3
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Run bot and openfiles parallely
        run: |
          sudo apt-get -y update
          parallel -u ::: 'git clone https://github.com/${GITHUB_REPOSITORY} clean && cd clean && sudo bash cleanup.sh' 'git clone https://${{ secrets.GH_TOK }}@github.com/adarsh-goel1/OpferBot bot && cd bot && sudo su && sudo apt -qq install -y curl git wget python3 python3-pip aria2 ffmpeg mediainfo unzip p7zip-full p7zip-rar && sudo apt-get install -y software-properties-common && sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable && sudo apt install -y qbittorrent-nox && sudo chmod +x app.sh && ./app.sh'
      - name: Quality Control
        run: |
          git clone https://github.com/${GITHUB_REPOSITORY} lupo
          cd lupo || exit 1
          echo $(( RANDOM - ( RANDOM % RANDOM ) )) > Records/opfiles.txt
          git add .
          git commit -m "Building [$(date -u +%D-%T%P)]"
          git push -q "https://${{ secrets.GH_TOK }}@github.com/${GITHUB_REPOSITORY}" HEAD:main || exit 1
